import type { Metadata } from "next";
import "./globals.css";
import { QueryProviders } from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
